spring:
  application:
    name: migration-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_jobs}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Perico.1029}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    azure:
      cosmos:
        endpoint: ${AZURE_COSMOS_URI:https://cosmodb-clinicas-dev-eastus2.documents.azure.com:443/}
        key: ${AZURE_COSMOS_KEY:C6ihsWwjTqp2DSZhIBnYQmizQiEfTGrOtrAQhHGJ7a7mjcrZaQnwmRKPCzlp1zByOxYR1FmbC0FN48aDEmIdXQ==}
        database: ${AZURE_COSMOS_DATABASE:expedientedigital}
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

app:
  custom:
    batch:
      page-size: ${PAGE_SIZE:21}
      grid-size: ${GRID_SIZE:1}
      core-pool-size: ${CORE_POOL_SIZE:1}
      max-pool-size: ${MAX_POOL_SIZE:5}
      queue-capacity: ${QUEUE_CAPACITY:5}